version: '3.8'

services:

  frontend: 
    build: 
      context: rekor-frontend
      args:
        - VITE_MONITOR_API=https://monitor.tsel.purdue.wtf/api/
    image: sigstoremonitor/monitor-frontend:test
    depends_on:
      - backend
    expose:
      - '3000' 
    networks:
      - frontnet

  backend:
    build: rekor-backend
    image: sigstoremonitor/monitor-backend:test
    environment:
      - DB_HOST=db
      - DB_NAME=monitor
      - DB_ROOT_PASSWORD=test
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backnet
      - frontnet
    expose:
      - '5000'

  proxy:
    build: proxy
    image: sigstoremonitor/monitor-proxy:test
    restart: always
    ports:
      - '80:80'
    depends_on:
      - frontend
    networks:
      - frontnet

  monitor:
    build: rekor-monitor
    image: sigstoremonitor/monitor-mirror:test
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=monitor
      - DB_PASSWORD=test
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backnet

  db:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MARIADB_DATABASE=monitor
      - MARIADB_ROOT_PASSWORD=test
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '--silent']
      interval: 3s
      retries: 5
      start_period: 30s
    networks:
      - backnet
    expose:
      - '3306'
    volumes:
      - monitor:/var/lib/mysql

volumes:
  monitor:

networks:
  backnet:
  frontnet:
